### ISSUE TITLE
I believe other type of softmax should be used

### ISSUE THREAD

**Issue by mikealche** [Vipermdl/ARL#1]
Hey there, 

I'm not completely sure Softmax2d does exactly what you what (apply the softmax spatially). 
I've implemented this paper by doing using that function at the start, but later I found out that that was a mistake. 

I believe that we should be doing this: 
1) Add a softmaxLayer to every bottleneck such that every bottleneck has a property
```
self.softmaxLayer = nn.Softmax(2) #it will apply softmax along the third dimension (we use 2 because we start indexing from 0)
```

and later override the forward function by doing this: 

```
 out = out + (identity 
                     * self.softmaxLayer(out.view(*out.size()[:2], -1)).view_as(out) 
                     * self.alpha) + (identity)
```

Tell me what you think

**Comment by Vipermdl** [comment]
Thanks! 
It'is my fault!
I will check this error when I have sparse time.
